<?php

/**
 * @file
 * report.module
 */

/**
 * Implements hook_theme().
 */
function report_theme() {
  return [
    'report-itog' => [
      'template' => 'rep-itog',
      'variables' => ['data' => []],
    ],
    'report-exkurs' => [
      'template' => 'rep-exkurs',
      'variables' => ['data' => []],
    ],
    'report-full' => [
      'template' => 'rep-full',
      'variables' => ['data' => []],
    ],
  ];
}
